import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import { Mulish } from "next/font/google";

const inter = Mulish({ subsets: ["latin"] });

export const metadata = {
  title: "Timeflix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
